### PR TITLE
Kwality koder/fix issues 32 and 33

### PR DESCRIPTION
**Pull request by KwalityKoder**
Fix issues 32 and 33

### CODE REVIEW

**Comment by KwalityKoder** [comment]
Fix issues 32 and 33

**Comment by RSuter** [comment]
Thanks for the pr. Is this ready?

**Comment by KwalityKoder** [comment]
Thanks for creating NuGetReferenceSwitcher in the first place - excellent work.

 

Yes the PR is ready - just pull from master on my fork.

**Comment by RSuter** [comment]
Where is FixUpNuGetReferences used?

**Comment by KwalityKoder** [comment]
Forget the branch - just pull from master. I removed that unused code there.

It was my original (failed ) attempt at getting rid of the SpecificVersion flag.

**Comment by KwalityKoder** [comment]
Any idea when the PR will be completed and a new release of NuGetReferenceSwitcher created? As you've noticed you'll need to delete the unused  FixUpNuGetReferences() mthod. Other than that this branch is basically the same as the last commit on master on my forked repo.

**Comment by RSuter** [comment]
[NuGetReferenceSwitcher.zip](https://github.com/RSuter/NuGetReferenceSwitcher/files/1362556/NuGetReferenceSwitcher.zip)

Can you test the extension? If it works, ill release it on the gallery..

**Comment by KwalityKoder** [comment]
OK will do.

**Comment by KwalityKoder** [comment]
It works in the sense that it fixes the two issues I raised.

**Pull request merged**
