### PR TITLE
Look for references in repositoryPath specified in NuGet.config file

### PR DESCRIPTION
**Pull request by mortengjesing**
This should fix issue 14 and issue 27.

### CODE REVIEW

**Comment by RSuter** [comment]
Thanks for the PR. Is this one ready to merge?

**Comment by mortengjesing** [comment]
Yes it is ready.

**Comment by mortengjesing** [comment]
Hi @RSuter - have you had time to look at the PR - any comments?

**Comment by RSuter** [comment]
Looks good. Thank you. My main problem is, that I could not upload a new VSIX version to the VS gallery - somehow it is broken and I havent heard back from Microsoft how to solve this...

**Pull request merged**
