### PR TITLE
Creating extension version to Visual Studio 2019

### PR DESCRIPTION
**Pull request by lucasrossoni**
Creating extension version to Visual Studio 2019

### CODE REVIEW

**Comment by RicoSuter** [comment]
Is this PR ready? I personally do not work on this project anymore but I can merge and publish the packages.

**Comment by lucasrossoni** [comment]
Hey Rico,

I'm using this version in my job, until now i don't found any bugs!

Thanks for share this helpfull extension



*____________________________________________Sds,**Lucas Rossoni*
*lucasrossoni@gmail.com <lucasrossoni@gmail.com>*



Em seg, 26 de ago de 2019 às 11:07, Rico Suter <notifications@github.com>
escreveu:

**Comment by SchreinerK** [comment]
Hello, 
Compiled with VS2019 CE, installed and works for me. 
The only thing I have made was to create a 00_Build_2019.bat

Thanks for this extension and thanks for the update
Best regards
Kay

**Review by SchreinerK — APPROVED** [review]

**Comment by Denchick** [comment]
Hi Rico! Thanks for this extension.

Could you merge and publish these changes?

**Comment by RicoSuter** [comment]
Should soon be available 
image

**Comment by RicoSuter** [comment]
https://marketplace.visualstudio.com/items?itemName=RicoSuter.NuGetReferenceSwitcherforVisualStudio2019

**Comment by Tychus** [comment]
Broken link ? can't seem to find it in the marketplace (2019 version)

**Comment by RicoSuter** [comment]
Sorry, it was not public, now it should work

**Pull request merged**
